
export const courseData =[
    {
        title:"CEH v12 EC COUNCIL",
        topics:[
            "Introduction to Ethical Hacking",
            "Foot Printing & Reconnaissance",
            "Scanning Network",
            "Enumeration",
            "Vulnerability Analysis",
            "System Hacking",
            "Malware Threats",
            "Sniffing",
            "Social Engineering",
            "Denial of Service",
            "Session Hijacking",
            "Evading IDS, Firewall & Honeypots",
            "Hacking Web Servers",
            "Hacking Web Applications",
            "SQL Injections",
            "Hacking Wireless Networks",
            "Hacking Mobile Platforms",
            "IOT Hacking",
            "Cloud Computing",
            "Cryptography"
        ],

        level:"Advance Diploma",
        duration:"240 hours",
        lecture:"hybrid",
        subject:"Information Security",
        language:["English", "Hindi"],
        materialIncludes:["Practice Labs", " Paid Tools", "Hack the Box/Try Hack me", "Paid Tools", "Videos, PDFs"]
    },


    {
        title:"Exploit Development",
        topics:[
            "Programming & Basics",
            "Assemble Language",
            "Debugging",
            "Stack Based Buffer Overflow",
            "Understanding windows Shellcode",
            "Heap Based Overflow",
            "Exploiting Safe SEH Protected Programs",
            "Bypassing DEP & ASLR",
            "Advance Shell - Coding",
            "Encoders & Writing Custom Encoders",
            "DLL Hijacking",
            "Client Side Exploits",
            "From Vulnerability to Exploit",
            "Metasploit Framework",
            "Binary Payloads & Antivirus Evasion",
            "Exploit to Metasploit"
        ],

        level:"Advance Diploma",
        duration:"240 hours",
        lecture:"hybrid",
        subject:"Information Security",
        language:["English", "Hindi"],
        materialIncludes:["Practice Labs", " Paid Tools", "Hack the Box/Try Hack me", "Paid Tools", "Videos, PDFs"]
    },

    {
        title:"Cyber Forensics",
        topics:[
            "Computer Forensics in Today’s World",
            "Computer Forensics Investigation Process",
            "Understanding Hard Disks & File System",
            "Data Acquisition & Duplication",
            "Defeating Anti-Forensics Techniques",
            "Windows Forensics",
            "Linux & MAC Forensics",
            "Network Forensics",
            "Investigating Web Attacks",
            "Dark Web Forensics",
            "Database Forensics",
            "Cloud Forensics",
            "Investigating Email Crimes",
            "Malware Forensics",
            "Mobile Forensics",
            "IOT Forensics"
        ],
        level:"Advance Diploma",
        duration:"240 hours",
        lecture:"hybrid",
        subject:"Information Security",
        language:["English", "Hindi"],
        materialIncludes:["Practice Labs", " Paid Tools", "Hack the Box/Try Hack me", "Paid Tools", "Videos, PDFs"]
    },

    {
        title:"API Penetration Testing",
        topics:[
            "Introduction to What is an API?",
            "Interacting with APIs",
            "Types of APIs",
            "API Security",
            "Lab Setup",
            "Tool Installation",
            "Burp Suite Introduction",
            "Postman Introduction",
            "Docker Introduction",
            "Enumerating APIs",
            "Introduction to Enumeration",
            "Fuzzing APIs",
            "Discovery via Source Code",
            "Attacking Authorization",
            "Introduction to Authorization",
            "BOLA Lab",
            "BFLA Labs",
            "Challenge solution",
            "Attacking Authentication",
            "Introduction to Authentication",
            "Attacking Tokens",
            "JSON Web Tokens - Part - 1 Theory",
            "JSON Web Tokens - Part - 2 JWTS",
            "JSON Web Tokens - Part - 3 JWT Tools",
            "Introduction to Injection Attacks",
            "Introduction to SQL Injections",
            "Mid-Course Capstone",
            "Mass Management",
            "NOSQL Injection Labs",
            "Mass Assignment",
            "Mass Assignment Labs",
            "Code Walkthrough",
            "Excessive Data Exposure",
            "Excessive Data Exposure Labs",
            "Challenge Solution",
            "SSRF Server Side Request Forgery",
            "Introduction to SSRF",
            "SSRF Labs"
        ],
        level:"Advance Diploma",
        duration:"240 hours",
        lecture:"hybrid",
        subject:"Information Security",
        language:["English", "Hindi"],
        materialIncludes:["Practice Labs", " Paid Tools", "Hack the Box/Try Hack me", "Paid Tools", "Videos, PDFs"]
    },

    {
        title:"Mobile Penetration Testing",
        topics:[
            "Introduction to Android Penetration’s Testing",
            "Preparing Kali Linux and Genymotion",
            "Using ADB & Installing Apps",
            "Decompiling Android Application",
            "Dex File Analysis",
            "Capturing Android Traffic",
            "Insecure Logging",
            "Hardcoding Issues Part - 1",
            "Insecure Data Storage Part - 1",
            "Insecure Data Storage Part - 2",
            "Insecure Data Storage Part - 3",
            "Insecure Data Storage Part - 4",
            "Input Validation Issue Part - 1",
            "Input Validation Issue Part - 2",
            "Access Control Issue Part - 1",
            "Access Control Issue Part - 3",
            "Hardcoding Issues Part - 2",
            "Input Validation Issue Part - 3",
            "SSL Pinning Bypass",
            "IOS Pen Testing"
        ],

        
    },

    {
        title:"Web Penetration Testing",
        topics:[
            "Introduction to Penetration Testing",
            "Web Application Introduction & API",
            "Session & Cookies",
            "PHP Programming Basics",
            "Cross Site Scripting Attacks: Manual",
            "Indepth Advance SQL Injections",
            "Cross Site Request Forgery in Depth",
            "Host Header Injection",
            "Hacking Web Server with Metasploit",
            "Brute Forcing Web App/No Rate Limit",
            "Server Side Request Forgery",
            "Subdomain Taker Over",
            "Writing Report Reporting Bugs",
            "Web Password Poisoning on Reset Function",
            "Privilege Escalation Injection",
            "Vertical",
            "Horizontal",
            "Remote Code Execution",
            "Directory Traversal"
        ],
        level:"Advance Diploma",
        duration:"240 hours",
        lecture:"hybrid",
        subject:"Information Security",
        language:["English", "Hindi"],
        materialIncludes:["Practice Labs", " Paid Tools", "Hack the Box/Try Hack me", "Paid Tools", "Videos, PDFs"]
    },

    {
        title:"Certified Bug Bounty Hunter",
        topics:[
            "Introduction to IT",
            "Introduction to Cybersecurity",
            "What is Cyber Security?",
            "Security Engineering",
            "Governance and Compliance",
            "Risk Management and Threat Intelligence",
            "Security Operations",
            "Education",
            "Network Security",
            "Cloud Security",
            "Endpoint Security",
            "Mobile Security",
            "Application Security",
            "Advanced Persistent Cybersecurity Threats",
            "Phishing Attacks",
            "Malware Detection",
            "Gen V Malware",
            "Cybersecurity Trends",
            "Cybersecurity User Protection",
            "Network Security",
            "Application Security",
            "Information Security",
            "Operational Security",
            "Disaster Recovery and Business Continuity",
            "End-User Education",
            "Setting up Hacking Machine",
            "Introduction to Networking",
            "Web Application Fundamentals & Configurations",
            "Introduction to Web Application Security Testing",
            "Web Application Reconnaissance",
            "Working with Burp suite",
            "Exploiting Traditional Web Application Vulnerabilities",
            "Introduction to Session Managements",
            "Introduction to XSS (Cross-Site Scripting)",
            "Introduction to SQL injection",
            "Introduction to File Inclusion Vulnerability",
            "CSRF (Cross-Site Request Forgery Attack)",
            "SSRF (Server-Side Request Forgery Attack)",
            "IDOR (Insecure Direct Object Reference)",
            "OS Command injection",
            "Response Manipulation",
            "Host Header Injection",
            "Parameter Tampering",
            "XXE (XML External Entity)",
            "RCE (Remote Code Execution)",
            "Introduction to Bug Bounty Platforms"
        ],
        level:"Advance Diploma",
        duration:"240 hours",
        lecture:"hybrid",
        subject:"Information Security",
        language:["English", "Hindi"],
        materialIncludes:["Practice Labs", " Paid Tools", "Hack the Box/Try Hack me", "Paid Tools", "Videos, PDFs"]
    }
]